# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generated_file.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from clickable_label import ClickableLabel


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image_chooser_button = QtWidgets.QPushButton(self.centralwidget)
        self.image_chooser_button.setGeometry(QtCore.QRect(550, 10, 161, 91))
        self.image_chooser_button.setObjectName("image_chooser_button")
        self.image = ClickableLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(6, 12, 531, 311))
        self.image.setText("")
        self.image.setObjectName("image")
        self.point_list = QtWidgets.QListWidget(self.centralwidget)
        self.point_list.setGeometry(QtCore.QRect(550, 110, 161, 192))
        self.point_list.setObjectName("point_list")
        self.zoom_in_button = QtWidgets.QPushButton(self.centralwidget)
        self.zoom_in_button.setGeometry(QtCore.QRect(550, 310, 75, 41))
        self.zoom_in_button.setObjectName("zoom_in_button")
        self.zoom_out_button = QtWidgets.QPushButton(self.centralwidget)
        self.zoom_out_button.setGeometry(QtCore.QRect(640, 310, 75, 41))
        self.zoom_out_button.setObjectName("zoom_out_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.image_chooser_button.setText(_translate("MainWindow", "Choose image"))
        self.zoom_in_button.setText(_translate("MainWindow", "Zoom in"))
        self.zoom_out_button.setText(_translate("MainWindow", "Zoom out"))
